### ISSUE TITLE
Getting an error when trying to run the examples

### ISSUE THREAD

**Issue by avioli** [nativeshell/nativeshell#179]
Trying to run your example and getting an error:

```
~/repos/examples> env RUST_BACKTRACE=1 cargo run
   Compiling nativeshell_examples v0.1.0 (/Users/avioli/repos/examples)
error: failed to run custom build command for `nativeshell_examples v0.1.0 (/Users/avioli/repos/examples)`

Caused by:
  process didn't exit successfully: `/Users/avioli/repos/examples/target/debug/build/nativeshell_examples-a095089059fed315/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=framework=/Users/avioli/repos/examples/target/debug
  cargo:rustc-link-lib=framework=path_provider_macos
  cargo:rustc-link-lib=framework=NativeShellPods
  cargo:rustc-link-lib=framework=shared_preferences_macos
  cargo:rustc-link-lib=framework=package_info_plus_macos
  cargo:rustc-link-lib=framework=url_launcher_macos
  cargo:rustc-link-search=framework=/Users/avioli/repos/examples/target/debug/build/nativeshell_examples-51d5436af0bcecd6/out/flutter

  ** Build failed with error **

  Flutter artifact location path at "/Users/avioli/fvm/versions/stable/bin/cache/artifacts/engine/darwin-arm64" does not exist! Try running 'flutter precache'

  --- stderr
  thread 'main' panicked at 'explicit panic', build.rs:26:9
  stack backtrace:
     0: std::panicking::begin_panic
               at /private/tmp/rust-20221227-52235-au6ott/rustc-1.66.0-src/library/std/src/panicking.rs:607:12
     1: build_script_build::main
               at ./build.rs:26:9
     2: core::ops::function::FnOnce::call_once
               at /private/tmp/rust-20221227-52235-au6ott/rustc-1.66.0-src/library/core/src/ops/function.rs:251:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Exception: env exited with 101
```

Unsure what to do to further give you more info.

I ran `flutter precache` and there was no error or any output.

```sh
~/repos/examples> flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
~/repos/examples> flutter precache
~/repos/examples>
```

**Comment by knopp** [comment]
I updated the examples.

**Comment by avioli** [comment]
Perfect. Thanks.

Had to manually run `flutter pub get` to update my deps, otherwise the window management was throwing exceptions.
