### ISSUE TITLE
Issues with native plugin `media_kit`

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#199]
There seems to be an issue building certain native plugins when using nativeshell.

I can reproduce the issue with [media_kit](https://pub.dev/packages/media_kit) as well as [fvp](https://pub.dev/packages/fvp) and it seems to be an issue with relative paths, at least for media_kit though there where also issues because media_kit has many warnings in it's build which are reported as errors.

I've created a repository based on the nativeshell example repo [here](https://github.com/maxjoehnk/nativeshell_media_kit_reproduction).

I'm on Linux using the latest Flutter version (3.16.5).

<details>
  <summary>Build Logs</summary>
  
```
❯ cargo run
   Compiling nativeshell_examples v0.1.0 (/mnt/nvme/cargo-build/examples)
error: failed to run custom build command for `nativeshell_examples v0.1.0 (/mnt/nvme/cargo-build/examples)`

Caused by:
  process didn't exit successfully: `/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-08b71f667ffe7011/build-script-build` (ex❯ cargo run
   Compiling nativeshell_examples v0.1.0 (/mnt/nvme/cargo-build/examples)
error: failed to run custom build command for `nativeshell_examples v0.1.0 (/mnt/nvme/cargo-build/examples)`

Caused by:
  process didn't exit successfully: `/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-08b71f667ffe7011/build-script-build` (exit status: 101)
  --- stdout
  running: cd "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins" "-DCMAKE_INSTALL_PREFIX=/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build
  running: cd "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--config" "Debug" "--"
  [  9%] Building CXX object flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/media_kit_libs_linux_plugin.cc.o
  [ 27%] Built target url_launcher_linux_plugin
  [ 36%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/media_kit_video_plugin.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_sw.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output_manager.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_gl.cc.o
  [ 72%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output.cc.o

  --- stderr
  make[2]: *** No rule to make target 'mimalloc/out/release/mimalloc.o', needed by 'flutter/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET'.  Stop.
  make[1]: *** [CMakeFiles/Makefile2:136: flutter/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter_linux/flutter_linux.h:10,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_libs_linux/include/media_kit_libs_linux/media_kit_libs_linux_plugin.h:10,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_libs_linux/media_kit_libs_linux_plugin.cc:8:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter_linux/fl_basic_message_channel.h:12:10: fatal error: gio/gio.h: No such file or directory
     12 | #include <gio/gio.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  make[2]: *** [flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/build.make:76: flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/media_kit_libs_linux_plugin.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:162: flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/all] Error 2
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output_manager.h:12,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:16:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc: In function ‘void media_kit_video_plugin_handle_method_call(MediaKitVideoPlugin*, FlMethodCall*)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     43 |     VideoOutputConfiguration configuration_value = {};
        |                                                     ^
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/texture_sw.h:14,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output_manager.h:12,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output_manager.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc: In function ‘gboolean texture_sw_copy_pixels(FlPixelBufferTexture*, const guint8**, guint32*, guint32*, GError**)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:52:29: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     52 |     if (self->current_width != required_width ||
        |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:53:30: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     53 |         self->current_height != required_height) {
        |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  cc1plus: all warnings being treated as errors
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:104: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_sw.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/texture_gl.h:14,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:118: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output_manager.cc.o] Error 1
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:76: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/media_kit_video_plugin.cc.o] Error 1
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc: In function ‘gboolean texture_gl_populate_texture(FlTextureGL*, guint32*, guint32*, guint32*, guint32*, GError**)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:72:43: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     72 |     gboolean resize = self->current_width != required_width ||
        |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:73:44: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     73 |                       self->current_height != required_height;
        |                       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:90: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_gl.cc.o] Error 1
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc: In function ‘void video_output_init(VideoOutput*)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:75:50: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     75 |   self->configuration = VideoOutputConfiguration{};
        |                                                  ^
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:75:50: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:132: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:188: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/all] Error 2
  make: *** [Makefile:91: all] Error 2
  thread 'main' panicked at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.45/src/lib.rs:894:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtraceit status: 101)
  --- stdout
  running: cd "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins" "-DCMAKE_INSTALL_PREFIX=/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build
  running: cd "/mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--config" "Debug" "--"
  [  9%] Building CXX object flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/media_kit_libs_linux_plugin.cc.o
  [ 27%] Built target url_launcher_linux_plugin
  [ 36%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/media_kit_video_plugin.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_sw.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output_manager.cc.o
  [ 63%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_gl.cc.o
  [ 72%] Building CXX object flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output.cc.o

  --- stderr
  make[2]: *** No rule to make target 'mimalloc/out/release/mimalloc.o', needed by 'flutter/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET'.  Stop.
  make[1]: *** [CMakeFiles/Makefile2:136: flutter/media_kit_libs_linux/CMakeFiles/MIMALLOC_TARGET.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter_linux/flutter_linux.h:10,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_libs_linux/include/media_kit_libs_linux/media_kit_libs_linux_plugin.h:10,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_libs_linux/media_kit_libs_linux_plugin.cc:8:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter_linux/fl_basic_message_channel.h:12:10: fatal error: gio/gio.h: No such file or directory
     12 | #include <gio/gio.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  make[2]: *** [flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/build.make:76: flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/media_kit_libs_linux_plugin.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:162: flutter/media_kit_libs_linux/CMakeFiles/media_kit_libs_linux_plugin.dir/all] Error 2
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output_manager.h:12,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:16:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc: In function ‘void media_kit_video_plugin_handle_method_call(MediaKitVideoPlugin*, FlMethodCall*)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     43 |     VideoOutputConfiguration configuration_value = {};
        |                                                     ^
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/media_kit_video_plugin.cc:43:53: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/texture_sw.h:14,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output_manager.h:12,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output_manager.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc: In function ‘gboolean texture_sw_copy_pixels(FlPixelBufferTexture*, const guint8**, guint32*, guint32*, GError**)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:52:29: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     52 |     if (self->current_width != required_width ||
        |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_sw.cc:53:30: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     53 |         self->current_height != required_height) {
        |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  cc1plus: all warnings being treated as errors
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:104: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_sw.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/texture_gl.h:14,
                   from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:118: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output_manager.cc.o] Error 1
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:76: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/media_kit_video_plugin.cc.o] Error 1
  In file included from /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:9:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:23:44: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     23 |   _VideoOutputConfiguration(gint64 width = NULL,
        |                                            ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/include/media_kit_video/video_output.h:24:45: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     24 |                             gint64 height = NULL,
        |                                             ^~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc: In function ‘gboolean texture_gl_populate_texture(FlTextureGL*, guint32*, guint32*, guint32*, guint32*, GError**)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:72:43: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     72 |     gboolean resize = self->current_width != required_width ||
        |                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/texture_gl.cc:73:44: error: comparison of integer expressions of different signedness: ‘guint32’ {aka ‘unsigned int’} and ‘gint32’ {aka ‘int’} [-Werror=sign-compare]
     73 |                       self->current_height != required_height;
        |                       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:90: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/texture_gl.cc.o] Error 1
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc: In function ‘void video_output_init(VideoOutput*)’:
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:75:50: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
     75 |   self->configuration = VideoOutputConfiguration{};
        |                                                  ^
  /mnt/nvme/cargo-build/examples/target/debug/build/nativeshell_examples-7862310dfca313c2/out/plugins/flutter/media_kit_video/video_output.cc:75:50: error: converting to non-pointer type ‘long int’ from NULL [-Werror=conversion-null]
  cc1plus: all warnings being treated as errors
  make[2]: *** [flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/build.make:132: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/video_output.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:188: flutter/media_kit_video/CMakeFiles/media_kit_video_plugin.dir/all] Error 2
  make: *** [Makefile:91: all] Error 2
  thread 'main' panicked at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.45/src/lib.rs:894:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
  
  </details>

**Comment by satheeshps** [comment]
@maxjoehnk Where you able to resolve this issue

**Comment by maxjoehnk** [comment]
Sadly no, though I've also not prioritized this issue further.
