### ISSUE TITLE
Doesn't run on linux using flutter 3.22+

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#225]
As I've alluded to in #224 nativeshell applications doesn't run on linux using flutter 3.22+

The following is the stacktrace & relevant logs from the application on flutter 3.22.0.

```
** Help me make NativeShell and Flutter on desktop better!
** We have a long way to go: https://nativeshell.dev/roadmap


** (mizer:281696): CRITICAL **: 12:31:15.937: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (mizer:281696): CRITICAL **: 12:31:15.937: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (mizer:281696): CRITICAL **: 12:31:15.937: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(mizer:281696): GLib-GObject-CRITICAL **: 12:31:15.937: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (mizer:281696): CRITICAL **: 12:31:15.937: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (mizer:281696): CRITICAL **: 12:31:15.937: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (mizer:281696): CRITICAL **: 12:31:15.937: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
thread 'main' panicked at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.14.8/src/object.rs:1070:1:
assertion failed: crate::types::instance_of::<Self>(ptr as *const _)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:148:5
   3: <glib::object::Object as glib::translate::FromGlibPtrNone<*mut gobject_sys::GObject>>::from_glib_none
             at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.14.8/src/object.rs:770:17
   4: <O as nativeshell::shell::platform::platform_impl::flutter::ViewExt>::get_engine
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/platform/linux/flutter.rs:58:13
   5: nativeshell::shell::platform::platform_impl::engine::PlatformEngine::new
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/platform/linux/engine.rs:35:21
   6: nativeshell::shell::engine::FlutterEngine::new
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/engine.rs:15:31
   7: nativeshell::shell::engine_manager::EngineManager::create_engine
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/engine_manager.rs:35:26
   8: nativeshell::shell::window_manager::WindowManager::create_window
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/window_manager.rs:84:33
   9: mizer_ui::run
             at ./crates/ui/src/lib.rs:106:5
  10: mizer::ui::run
             at ./crates/mizer/src/main.rs:135:9
  11: mizer::main
             at ./crates/mizer/src/main.rs:32:9
  12: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I've looked for changes in the flutter engine that may cause these issues but I didn't notice any relevant changes.
I'm still looking into fixing this myself but might need some help as my lack of gtk knowledge as well as missing c/c++ debugging experience are not really helpful.

**Comment by maxjoehnk** [comment]
I've pushed a branch of the examples repo to reproduce the issue:

https://github.com/maxjoehnk/nativeshell_examples/tree/feature/flutter-3.22-linux-not-working


Here the application crashes with the following stacktrace:

```
/usr/bin/cargo run --color=always --profile dev
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/nativeshell_examples`

** Help me make NativeShell and Flutter on desktop better!
** We have a long way to go: https://nativeshell.dev/roadmap

thread 'main' panicked at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.14.0/src/object.rs:1070:1:
assertion failed: crate::types::instance_of::<Self>(ptr as *const _)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:148:5
   3: <glib::object::Object as glib::translate::FromGlibPtrNone<*mut gobject_sys::GObject>>::from_glib_none
             at /home/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.14.0/src/object.rs:770:17
   4: <O as nativeshell::shell::platform::platform_impl::flutter::ViewExt>::get_engine
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/platform/linux/flutter.rs:58:13
   5: nativeshell::shell::platform::platform_impl::engine::PlatformEngine::new
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/platform/linux/engine.rs:35:21
   6: nativeshell::shell::engine::FlutterEngine::new
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/engine.rs:15:31
   7: nativeshell::shell::engine_manager::EngineManager::create_engine
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/engine_manager.rs:35:26
   8: nativeshell::shell::window_manager::WindowManager::create_window
             at /home/max/.cargo/git/checkouts/nativeshell-fcaea95c5e19c59f/36ceab5/nativeshell/src/shell/window_manager.rs:84:33
   9: nativeshell_examples::main
             at ./src/main.rs:34:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```
