### ISSUE TITLE
Error when building with github CI

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#72]
`cargo build --release` ended with error on github ci

<details>
<summary>Final Logs</summary>

```
error: failed to run custom build command for `appimagepool v2.1.0 (/home/runner/work/appimagepool/appimagepool)`

Caused by:
  process didn't exit successfully: `/home/runner/work/appimagepool/appimagepool/target/release/build/appimagepool-3ccdf5477e6f6792/build-script-build` (exit status: 101)
  --- stdout

  ** Build failed with error **

  External Tool Failed!
  Status: ExitStatus(ExitStatus(256))
  Command: "/opt/hostedtoolcache/flutter/2.5.0-5.2.pre-beta/x64/bin/flutter" "assemble" "--output=." "--define=BuildMode=release" "--define=TargetPlatform=linux-x64" "--define=DarwinArchs=" "--define=TargetFile=../../../../../../lib/main.dart" "-v" "--suppress-analytics" "release_bundle_linux-x64_assets"
  Stderr:
  [  +27 ms] Target unpack_linux failed: Exception: Unsupported file type "notFound" for /opt/hostedtoolcache/flutter/2.5.0-5.2.pre-beta/x64/bin/cache/artifacts/engine/linux-x64-release/libflutter_linux_gtk.so
             #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:33:7)
             #1      UnpackLinux.build (package:flutter_tools/src/build_system/targets/linux.dart:72:29)
             #2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
             <asynchronous suspension>
             #3      Future.wait.<anonymous closure> (dart:async/future.dart)
             <asynchronous suspension>
             #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
             <asynchronous suspension>
             #5      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
             <asynchronous suspension>
             #6      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
             <asynchronous suspension>
             #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
             <asynchronous suspension>
             #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
             <asynchronous suspension>
             #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
             <asynchronous suspension>
             #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
             <asynchronous suspension>
             #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
             <asynchronous suspension>
             #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #15     main (package:flutter_tools/executable.dart:92:3)
             <asynchronous suspension>

  [   +5 ms] Target aot_elf_release failed: ProcessException: Failed to find "/opt/hostedtoolcache/flutter/2.5.0-5.2.pre-beta/x64/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot" in the search path.
               Command: /opt/hostedtoolcache/flutter/2.5.0-5.2.pre-beta/x64/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot 
             #0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
             #1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
             #2      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
             #3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
             #4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
             #5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
             #6      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
             #7      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:207:56)
             #8      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:276:52)
             #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:27)
             <asynchronous suspension>
             #10     Future.wait.<anonymous closure> (dart:async/future.dart)
             <asynchronous suspension>
             #11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
             <asynchronous suspension>
             #12     Future.wait.<anonymous closure> (dart:async/future.dart)
             <asynchronous suspension>
             #13     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
             <asynchronous suspension>
             #14     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
             <asynchronous suspension>
             #15     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
             <asynchronous suspension>
             #16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
             <asynchronous suspension>
             #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #18     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
             <asynchronous suspension>
             #19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
             <asynchronous suspension>
             #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
             <asynchronous suspension>
             #22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
             <asynchronous suspension>
             #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #24     main (package:flutter_tools/executable.dart:92:3)
             <asynchronous suspension>

  [   +4 ms] 
             #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
             #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
             <asynchronous suspension>
             #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
             <asynchronous suspension>
             #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
             <asynchronous suspension>
             #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
             <asynchronous suspension>
             #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
             <asynchronous suspension>
             #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
             <asynchronous suspension>
             #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #10     main (package:flutter_tools/executable.dart:92:3)
             <asynchronous suspension>
```

</details>

**Comment by prateekmedia** [comment]
It turns out it was my fault, I have not set `flutter config --enable-linux-desktop` in the CI first before building.
